# Assignment 2
### Python Assignment: Data Structures, Functions, Numpy & Pandas
By **Mohan Sirumalla**
***
## Assignment Questions
### Section A: Data Structures & Control Structures

1.	Create a list of 5 integers. Perform and print the result of the following operations: **append, extend, insert, remove, pop, clear, index, count, sort, and reverse**.

In [28]:
# List of 5 integers
list_int = [15,12,25,43,21] # store the integers in a list
print("Original List",list_int)
# --> append() adds element at the end of the list
list_int.append(10)
print("After append " ,list_int)
# --> extend() adds mutliple elements at the end of the list
list_int.extend([20,10])
print("After extend " ,list_int)
# --> insert() adds element at a specific position
list_int.insert(2,30)
print("After insert " ,list_int)
# --> remove() removes the first occurrence of a element
list_int.remove(10)
print("After remove " ,list_int)
# --> pop() removes the last element
list_int.pop()
print("After pop    " ,list_int)
# --> clear() removes all the items
list_int.clear()
print("After clear  " ,list_int)
# --> index() searched
#list_int.index(0) # it will given error list is empty now
# to continue need to add items in the list
list_int.extend([50, 40, 10, 20, 30]) 
list_int.index(20)
# --> count() of particular item in the list

print("Count of 12 in the list =" ,list_int.count(12) )
# --> reverse
print("Before reverse",list_int)
list_int.reverse()
print("After reverse ",list_int)
# --> sort the items in the order
list_int.sort()
print("after sort    ", list_int)
# --> sort the items in the order
list_int.sort(reverse=True)
print("after sort descending    ", list_int)

Original List [15, 12, 25, 43, 21]
After append  [15, 12, 25, 43, 21, 10]
After extend  [15, 12, 25, 43, 21, 10, 20, 10]
After insert  [15, 12, 30, 25, 43, 21, 10, 20, 10]
After remove  [15, 12, 30, 25, 43, 21, 20, 10]
After pop     [15, 12, 30, 25, 43, 21, 20]
After clear   []
Count of 12 = 0
Before reverse [50, 40, 10, 20, 30]
After reverse  [30, 20, 10, 40, 50]
after sort     [10, 20, 30, 40, 50]
after sort descending     [50, 40, 30, 20, 10]

2.	Create a **tuple** that stores 3 student names. Try **changing** the second name in the tuple. What happens? Explain why.

In [3]:
# create a tuple 
tuple_stu_nm =("Mohan","Sohan","Rohan")
print("Student Names",tuple_stu_nm)
print("First  Student Name",tuple_stu_nm[0])
print("Second Student Name",tuple_stu_nm[1])
tuple_stu_nm[1]="Tina"

Student Names ('Mohan', 'Sohan', 'Rohan')
First  Student Name Mohan
Second Student Name Sohan

TypeError: 'tuple' object does not support item assignment

**Tuple** are similar to **list**, but there is a **differnce**
- **immutable** cannot change

3.	Create a **set** of integers with some duplicate values. Print the set and explain the **output**.

In [39]:
# Sets
set_int_dup= {30,10,20,20,10}
print("Set of Duplicate Numbers", set_int_dup)

Set of Duplicate Numbers {10, 20, 30}

Sets **DO NOT** contain duplicate values, So it will accepts duplicate values only once, <br/>
So it will not show the duplicate values

4.	Create a **dictionary** with the keys: '**name**', '**age**', and '**city**'. Update the age and add a new key '**email**'. Print the final dictionary.

In [74]:
# create dictionary
dict_person = {"name":"Mohan","age":52,"city":"Mumbai"}
#print(type(dict_person)) # to check is it dictionary
#print("Person  = ",dict_person)
dict_person["age"]=32 # update the age
#print("After age change",dict_person)
dict_person.update({"email":"sirumala.mohan@gmail.com"})
print("Person details",dict_person)

Person details {'name': 'Mohan', 'age': 32, 'city': 'Mumbai', 'email': 'sirumala.mohan@gmail.com'}

5. Write a **script** that checks if a person is eligible to **vote** age ≥ 18). Take age as a variable and print the appropriate message

In [7]:
# using simple variable age
# age = 23
try:
    age = int(input("Enter Age"))
    if age>=18:
        print ("Eligible for vote")
    else:
        print ("Not eligible for vote")
except ValueError:
    print ("Eligible for vote")

Enter Age 12

Not eligible for vote

6.	Given a '**marks**' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [84]:
# Script to print the grages based on marks
int_marks = 90 #80 #60 # 20 # 
# if and else condition to check
if int_marks >=90: # 90 and above: 'A'
    print("A")
elif int_marks >=75: #75–89: 'B'
    print("B")
elif int_marks >=50: # 50–74: 'C'
    print("C")
else: # Below 50: 'Fail'
    print("Fail")

A

7. Given a **number**, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [106]:
# to check number positive even,  zero, negative
int_num =  -1 # -2 # 3  #4

if int_num > 0 and  int_num%2 ==0:
    print ("Number is Positive and Even")
elif int_num == 0 :
        print ("Number is Zero")
elif int_num < 0  :
        print ("Number is Negative")
else:
        print ("Number is Posivite")
# End of script

Number is Negative

### Section B: Numpy

8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [11]:
# for Numpy need to import Numpy library
import numpy as np

In [19]:
# scalar using np.array(5)
#
scalar = np.array(5)
print(f"Scalar Value : {scalar}")
print("-----------------")
#print(f"Shape of Scalar Value : {scalar.shape}")
# A 1D array with values 1 to 5 numbers
arr_num_1d = np.array([1, 2, 3, 4, 5])
print(f"1D Array : {arr_num_1d}")
print(f"Shape of 1D Array : {arr_num_1d.shape}")
print("-----------------")
#print(type(arr_num)) 
# 2D array (2X3)
arr_num_2d = np.array([[1, 2, 3],[4,5,6]])
print(f"2D Array :\n {arr_num_2d}")
print(f"Shape of 2D Array : {arr_num_2d.shape}")

Scalar Value : 5
-----------------
1D Array : [1 2 3 4 5]
Shape of 1D Array : (5,)
-----------------
2D Array :
 [[1 2 3]
 [4 5 6]]
Shape of 2D Array : (2, 3)

9. Generate a **4x4** Numpy array of random integers between 0 and 100 using np.random.randint().

In [59]:
# 2D array (4X4)
arr_num_4 = np.random.randint(0, 101, (4, 4))
print(arr_num_4)

[[ 49  19  31  26]
 [ 47  13  68  18]
 [ 30  29  96  65]
 [ 74 100   5  30]]

### Section C: Exploring Pandas

11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

####  A Use .info(), .describe()

In [28]:
# Create a manual Datarame
#need to import pandas library
import pandas as pd
import numpy as np # numpy for null value
data = {
    'Name': ['Mohan', 'Sohan', 'Rohan','Tina','Mina','Naina','Heena','Mahesh','Dinesh','Mohan'],
    'Age':  [45,30,40,31,35,47, 35,34,42,45],
    'City': ['Delhi', 'Mumbai', 'Bangalore','Bangalore','Mumbai', 'Mumbai','Delhi','Kolkata' ,'Surat','Delhi'],
    'Salary': [30000.00,35000.00,42000.00,47000.00,np.nan,np.nan,32000.00,41000.00,50000.00,30000.00]
}
df = pd.DataFrame(data)
print(df)

     Name  Age       City   Salary
0   Mohan   45      Delhi  30000.0
1   Sohan   30     Mumbai  35000.0
2   Rohan   40  Bangalore  42000.0
3    Tina   31  Bangalore  47000.0
4    Mina   35     Mumbai      NaN
5   Naina   47     Mumbai      NaN
6   Heena   35      Delhi  32000.0
7  Mahesh   34    Kolkata  41000.0
8  Dinesh   42      Surat  50000.0
9   Mohan   45      Delhi  30000.0

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   City    10 non-null     object
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

In [29]:
df.describe()

             Age        Salary
count  10.000000      8.000000
mean   38.400000  38375.000000
std     6.186006   7763.237543
min    30.000000  30000.000000
25%    34.250000  31500.000000
50%    37.500000  38000.000000
75%    44.250000  43250.000000
max    47.000000  50000.000000

####  B Select 'Name' and 'City' columns

In [30]:
df[['Name','City']]

     Name       City
0   Mohan      Delhi
1   Sohan     Mumbai
2   Rohan  Bangalore
3    Tina  Bangalore
4    Mina     Mumbai
5   Naina     Mumbai
6   Heena      Delhi
7  Mahesh    Kolkata
8  Dinesh      Surat
9   Mohan      Delhi

#### C Drop 'City' column

In [34]:
df_org=df # Taking backup

In [38]:
df.drop('City',axis=1,inplace=True) # permanently remove the column from the data set

In [40]:
df # check the city column is exist in the dataset just to confirm

     Name  Age   Salary
0   Mohan   45  30000.0
1   Sohan   30  35000.0
2   Rohan   40  42000.0
3    Tina   31  47000.0
4    Mina   35      NaN
5   Naina   47      NaN
6   Heena   35  32000.0
7  Mahesh   34  41000.0
8  Dinesh   42  50000.0
9   Mohan   45  30000.0

#### D. Fill any missing values in 'Salary' column with the mean

In [50]:
df[['Salary']].isnull() # to check any missint values

   Salary
0   False
1   False
2   False
3   False
4   False
5   False
6   False
7   False
8   False
9   False

In [45]:
df['Salary'].mean() # check the mean of salary colunm

np.float64(38375.0)

In [47]:
df['Salary']=df['Salary'].fillna(df['Salary'].mean())# replace null values in the Salary with Average (mean values)

In [48]:
df

     Name  Age   Salary
0   Mohan   45  30000.0
1   Sohan   30  35000.0
2   Rohan   40  42000.0
3    Tina   31  47000.0
4    Mina   35  38375.0
5   Naina   47  38375.0
6   Heena   35  32000.0
7  Mahesh   34  41000.0
8  Dinesh   42  50000.0
9   Mohan   45  30000.0

#### E. Remove any duplicate rows

In [55]:
duplicates = df[df.duplicated()] # duplicated(keep=False) to include the first occurrence

In [56]:
duplicates

    Name  Age   Salary
9  Mohan   45  30000.0

In [58]:
# to check duplicate rows
print(f"Duplicate rows {df.duplicated().sum()}")

Duplicate rows 1

In [59]:
df.drop_duplicates()

     Name  Age   Salary
0   Mohan   45  30000.0
1   Sohan   30  35000.0
2   Rohan   40  42000.0
3    Tina   31  47000.0
4    Mina   35  38375.0
5   Naina   47  38375.0
6   Heena   35  32000.0
7  Mahesh   34  41000.0
8  Dinesh   42  50000.0

In [61]:
df_with_duplicates=df # backup of duplicates

In [64]:
df=df.drop_duplicates() # reassinged  with no duplicates

In [66]:
df # to confirm

     Name  Age   Salary
0   Mohan   45  30000.0
1   Sohan   30  35000.0
2   Rohan   40  42000.0
3    Tina   31  47000.0
4    Mina   35  38375.0
5   Naina   47  38375.0
6   Heena   35  32000.0
7  Mahesh   34  41000.0
8  Dinesh   42  50000.0